import {Product} from "@/types/products";

export const DATA_PRODUCTS: Product[] = [
    {
        id: "pm12",
        name: "Patient Monitor PM‑12",
        brand: "MediLine",
        model: "PM-12A",
        sku: "MED-PM12A",
        description: "Monitor pasien multi‑parameter untuk ICU/IGD/OK.",
        imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=1600&auto=format&fit=crop",
        badges: ["Best Seller"],
        specs: [
            "Layar 12.1\" TFT, resolusi 1280×800",
            "Parameter: ECG, SpO₂, NIBP, RESP, TEMP",
            "Tren data 120 jam, alarm audio‑visual",
            "Baterai internal hingga 4 jam",
        ],
        certifications: ["ISO 13485", "CE"],
        warranty: "12 Bulan Servis & Sparepart",
        inStock: true,
        href: "#",
        rates: [
            { unit: "bulan", price: 3_500_000, originalPrice: 3_900_000, minTerm: 1 },
            { unit: "minggu", price: 1_100_000, minTerm: 2 },
            { unit: "hari", price: 200_000, minTerm: 3 },
        ],
    },
    {
        id: "ip700",
        name: "Infusion Pump IP‑700",
        brand: "CareFlow",
        model: "IP-700",
        sku: "CF-IP700",
        description: "Pompa infus akurat dengan mode VTBI dan KVO.",
        imageUrl: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?q=80&w=1600&auto=format&fit=crop",
        badges: ["Promo"],
        specs: [
            "Akurasi ±2%, rate 1–1200 mL/jam",
            "Kompatibel dengan berbagai set infus",
            "Alarm oklusi, pintu terbuka, udara",
            "Mode bolus & anti‑bolus",
        ],
        certifications: ["ISO 13485", "CE", "e‑Katalog*"],
        warranty: "24 Bulan Servis",
        inStock: true,
        href: "#",
        rates: [
            { unit: "bulan", price: 2_250_000, originalPrice: 2_500_000 },
            { unit: "minggu", price: 800_000 },
        ],
    },
    {
        id: "sp300",
        name: "Suction Pump SP‑300",
        brand: "SurgiPro",
        model: "SP-300",
        sku: "SP-SP300",
        description: "Portable suction pump untuk tindakan minor & ambulans.",
        imageUrl: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=1600&auto=format&fit=crop",
        badges: ["Baru"],
        specs: [
            "Daya hisap hingga 18 L/menit",
            "Vakum maksimal −75 kPa, adjustable",
            "Botol 1 L, autoclavable",
            "Noise < 55 dB",
        ],
        certifications: ["ISO 13485"],
        warranty: "12 Bulan Servis",
        inStock: false,
        href: "#",
        rates: [
            { unit: "bulan", price: 1_650_000 },
            { unit: "minggu", price: 600_000 },
        ],
    },
];
